# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1e8a76dd05f4c8e35994aaa8f76b0e45ab04d4ab17fd0058b1e6b3efa341bce3e6e1a16046a94ef234e94a3623fcac07a303e109a869dba081385a104066a23

test:
  secret_key_base: 76ed9ad0d0637dd4f4365a26ac8b1c4bd92d7fa28a92b3d4cf05d35e10b5e04c3daf6ce30162ec51157ff1ab0114fce874384a9a7e9756407d53a5042901fcee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
